server {
    listen 80;
    server_name zhanghaixin.top www.zhanghaixin.top;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    location /health {
        return 200 '{"status":"ok"}';
        add_header Content-Type application/json;
    }
}
